### ISSUE TITLE
Regression in tsed-cli@3.3.2: Cannot read property 'install' of undefined (cli-plugin-mocha)

### ISSUE THREAD

**Issue by jojoxd** [tsedio/tsed-cli#141]
## Information

- **Version:** 3.3.2
- **Install Method**: `sudo yarn global add @tsed/cli`

I've found a regression in 3.3.2 that was not in 3.3.1.

On version 3.3.2, this happens, while on 3.3.1 it finishes correctly.
```
? Choose the target platform: Express.js
? Choose the convention file styling: Ts.ED
? Check the features needed for your project GraphQL, Database, Passport.js, Socket.io, Testing, Commands
? Choose a ORM manager TypeORM
? Which TypeORM you want to install? MariaDB
? Choose unit framework Mocha + Chai + Sinon
? Choose the package manager: Yarn
  ↓ Write RC files [skipped]
  ✔ Install plugins
  ✔ Load plugins
  ❯ Install plugins dependencies
    ✖ Run plugin '@tsed/cli-plugin-mocha'
      → Cannot read property 'install' of undefined
      Run plugin '@tsed/cli-plugin-passport'
      Run plugin '@tsed/cli-plugin-typeorm'
      Install
TypeError: Cannot read property 'install' of undefined
    at CliHooks.emit (/usr/local/share/.config/yarn/global/node_modules/@tsed/cli-core/lib/services/CliHooks.js:17:68)
    at Task.task (/usr/local/share/.config/yarn/global/node_modules/@tsed/cli-core/lib/services/CliPlugins.js:33:43)
    at /usr/local/share/.config/yarn/global/node_modules/listr/lib/task.js:167:30
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  context: {
    root: '.',
    tsedVersion: 'latest',
    production: false,
    rawArgs: [],
    platform: 'express',
    convention: 'default',
    packageManager: 'yarn',
    projectName: 'tsed',
    graphql: true,
    db: true,
    passportjs: true,
    socketio: true,
    testing: true,
    commands: true,
    typeorm: true,
    mariadb: true,
    mocha: true,
    features: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    srcDir: 'src',
    npm: false,
    yarn: true,
    express: true,
    koa: false,
    platformSymbol: 'PlatformExpress',
    verbose: undefined
  }
}
```

**Comment by Romakita** [comment]
Thanks @jojoxd  for the opened issue ;)
