### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by Mysteriosis** [tsedio/tsed-cli#168]
Hello everyone,

I try to use the cli, I installed it with :
`yarn global add @tsed/cli`
(but tried with `npm` too, same result)

And when I want to use `tsed -h` or `tsed init .`, I have the error :
```
TypeError: Cannot read property 'get' of undefined
    at Provider.get (C:\Users\Iosis\AppData\Local\Yarn\Data\global\node_modules\@tsed\di\lib\index.js:187:23)
    at Provider.get configuration [as configuration] (C:\Users\Iosis\AppData\Local\Yarn\Data\global\node_modules\@tsed\di\lib\index.js:179:17)
    at C:\Users\Iosis\AppData\Local\Yarn\Data\global\node_modules\@tsed\di\lib\index.js:1792:20
    at Map.forEach (<anonymous>)
    at Map.resolveConfiguration (C:\Users\Iosis\AppData\Local\Yarn\Data\global\node_modules\@tsed\di\lib\index.js:1791:11)
    at Map.bootstrap (C:\Users\Iosis\AppData\Local\Yarn\Data\global\node_modules\@tsed\di\lib\index.js:1755:10)
    at Map.load (C:\Users\Iosis\AppData\Local\Yarn\Data\global\node_modules\@tsed\di\lib\index.js:1767:10)
    at Function.loadInjector (C:\Users\Iosis\AppData\Local\Yarn\Data\global\node_modules\@tsed\cli-core\lib\index.js:3593:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.bootstrap (C:\Users\Iosis\AppData\Local\Yarn\Data\global\node_modules\@tsed\cli-core\lib\index.js:3574:5)
```

Can you help / check please ?

Environment:
- Windows 10
- Node 14.17.6 (through nvm)
- Using GitBash

**Comment by Romakita** [comment]
Hello @Mysteriosis

Yes I'm sorry I'd just released a new version of Ts.ED that have a side effect on the CLI. The release is on going.

The fix will be released in few minutes. I'm sorry again for the disagreement 

See you
Romain

**Comment by Romakita** [comment]
@Mysteriosis  You can install now the latest version of the CLI.

**Comment by Mysteriosis** [comment]
Hi @Romakita

I just tested the cli again and everything seems to work perfectly.
You can close this ticket :)

Thanks for your great work !
Pierre-Alain
