### ISSUE TITLE
[BUG]  TypeGraphQL Installation fails

### ISSUE THREAD

**Issue by fredlemieux** [tsedio/tsed-cli#255]
## Information
I've had some trouble with `tsed init` where 'barrelsby --config .barrelsby.json' would fail due to the error: 
`Error: ENOENT: no such file or directory, scandir '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/src/datasources'\n`
I've managed to narrow this down to the TypeGraphQL feature.

I'm using an M1 Mac, Node.js v18.4.0.  I asked someone who was using a non-M1 mac to test this out and it fails with the same message. 

- **Version: 3.21.2  
- Logs:
```

tsed init .                      
feature/basic-express-server  ✱
? Choose the target platform: Express.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project TypeGraphQL
? Choose the package manager: NPM
↓ Write RC files [SKIPPED]
↓ Write RC files [SKIPPED]
✔ Install plugins
✔ Load plugins
✔ Install plugins dependencies
✔ Generate project files
/Users/frederiquelemieux/.nvm/versions/node/v18.4.0/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: npm run barrels
node:fs:1450
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/src/datasources'
    at Object.readdirSync (node:fs:1450:3)
    at buildTree (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/fileTree.js:13:32)
    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:46:51
    at Generator.next (<anonymous>)
    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:5:12)
    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:43:60
    at Array.forEach (<anonymous>)
    at Barrelsby (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:43:25) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/src/datasources'
}

Node.js v18.4.0

> app@1.0.0 barrels
> barrelsby --config .barrelsby.json

    at makeError (/Users/frederiquelemieux/.nvm/versions/node/v18.4.0/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/frederiquelemieux/.nvm/versions/node/v18.4.0/lib/node_modules/@tsed/cli/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: npm run barrels',
  command: 'npm run barrels',
  escapedCommand: 'npm run barrels',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n> app@1.0.0 barrels\n> barrelsby --config .barrelsby.json\n',
  stderr: 'node:fs:1450\n' +
    '  handleErrorFromBinding(ctx);\n' +
    '  ^\n' +
    '\n' +
    "Error: ENOENT: no such file or directory, scandir '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/src/datasources'\n" +
    '    at Object.readdirSync (node:fs:1450:3)\n' +
    '    at buildTree (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/fileTree.js:13:32)\n' +
    '    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:46:51\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:9:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:5:12)\n' +
    '    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:43:60\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Barrelsby (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/node_modules/barrelsby/bin/index.js:43:25) {\n' +
    '  errno: -2,\n' +
    "  syscall: 'scandir',\n" +
    "  code: 'ENOENT',\n" +
    "  path: '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/app/src/datasources'\n" +
    '}\n' +
    '\n' +
    'Node.js v18.4.0',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.4.0

```

**UPDATE:** if I run tsed command on it's own it says:
`[15:15:05][WARN] ✖ Fail to load plugin @tsed/cli-plugin-typegraphql`

**UPDATE-2:**
I've cloned this repo and run the  `yarn start:init:run` command and generated a tsed project with typegraphql and it worked fine?!  I'm a little unsure how to debug and diagnose the problem, but please let me know how I can help?

**UPDATE-3:** Tried installing all features used above but using the cloned Repo and got the same error:
```
yarn start:init:run                                                                                                                                       master 
yarn run v1.22.17
$ cross-env NODE_ENV=development cross-env CI=true ts-node -r tsconfig-paths/register src/bin/tsed.ts init -r ./.tmp/init/default
? Choose the target platform: Express.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project TypeGraphQL, Database, Passport.js, Testing, Linter
? Choose a ORM manager Prisma
? Choose unit framework Jest
? Choose linter tools framework EsLint
? Choose extra linter tools Prettier, Lint on commit
? Choose the package manager: NPM
[15:34:35] [START] Write RC files
[15:34:35] [SKIP] Write RC files
[15:34:35] [START] Install plugins
[15:34:35] [START] Write package.json
[15:34:35] [SUCCESS] Write package.json
[15:34:35] [START] Installing dependencies using npm
[15:34:35] [DATA] npm WARN config production Use `--omit=dev` instead.
[15:34:59] [DATA] npm WARN deprecated apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
[15:34:59] [DATA] npm WARN deprecated graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
[15:34:59] [DATA] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[15:34:59] [DATA] npm WARN deprecated apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
[15:34:59] [DATA] npm WARN deprecated subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
[15:34:59] [DATA] npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
[15:35:00] [DATA] added 214 packages, and audited 215 packages in 25s
[15:35:00] [DATA] 38 packages are looking for funding
[15:35:00] [DATA]   run `npm fund` for details
[15:35:00] [DATA] 5 high severity vulnerabilities
[15:35:00] [DATA] To address all issues (including breaking changes), run:
[15:35:00] [DATA]   npm audit fix --force
[15:35:00] [DATA] Run `npm audit` for details.
[15:35:00] [SUCCESS] Installing dependencies using npm
[15:35:00] [START] Add dependencies using npm
[15:35:31] [DATA] added 187 packages, and audited 402 packages in 31s
[15:35:31] [DATA] 47 packages are looking for funding
[15:35:31] [DATA]   run `npm fund` for details
[15:35:31] [DATA] 5 high severity vulnerabilities
[15:35:31] [DATA] To address all issues (including breaking changes), run:
[15:35:31] [DATA]   npm audit fix --force
[15:35:31] [DATA] Run `npm audit` for details.
[15:35:31] [SUCCESS] Add dependencies using npm
[15:35:31] [START] Add devDependencies using npm
[15:35:42] [DATA] added 80 packages, removed 20 packages, changed 2 packages, and audited 462 packages in 10s
[15:35:42] [DATA] 54 packages are looking for funding
[15:35:42] [DATA]   run `npm fund` for details
[15:35:42] [DATA] 5 high severity vulnerabilities
[15:35:42] [DATA] To address all issues (including breaking changes), run:
[15:35:42] [DATA]   npm audit fix --force
[15:35:42] [DATA] Run `npm audit` for details.
[15:35:42] [SUCCESS] Add devDependencies using npm
[15:35:42] [START] Clean
[15:35:42] [SUCCESS] Clean
[15:35:42] [SUCCESS] Install plugins
[15:35:42] [START] Load plugins
[15:35:43] ✔ @tsed/cli-plugin-eslint module loaded
[15:35:43] ✔ @tsed/cli-plugin-jest module loaded
[15:35:43] ✔ @tsed/cli-plugin-passport module loaded
[15:35:43] ✔ @tsed/cli-plugin-prisma module loaded
[15:35:43] ✔ @tsed/cli-plugin-typegraphql module loaded
[15:35:43] [SUCCESS] Load plugins
[15:35:43] [START] Install plugins dependencies
[15:35:43] [START] Run plugin '@tsed/cli-plugin-typegraphql'
[15:35:43] [SUCCESS] Run plugin '@tsed/cli-plugin-typegraphql'
[15:35:43] [START] Run plugin '@tsed/cli-plugin-passport'
[15:35:43] [SUCCESS] Run plugin '@tsed/cli-plugin-passport'
[15:35:43] [START] Run plugin '@tsed/cli-plugin-prisma'
[15:35:43] [SUCCESS] Run plugin '@tsed/cli-plugin-prisma'
[15:35:43] [START] Run plugin '@tsed/cli-plugin-jest'
[15:35:43] [SUCCESS] Run plugin '@tsed/cli-plugin-jest'
[15:35:43] [START] Run plugin '@tsed/cli-plugin-eslint'
[15:35:43] [SUCCESS] Run plugin '@tsed/cli-plugin-eslint'
[15:35:43] [START] Install
[15:35:43] [START] Write package.json
[15:35:43] [SUCCESS] Write package.json
[15:35:43] [START] Installing dependencies using npm
[15:35:43] [DATA] npm WARN config production Use `--omit=dev` instead.
[15:35:44] [DATA] up to date, audited 462 packages in 668ms
[15:35:44] [DATA] 54 packages are looking for funding
[15:35:44] [DATA]   run `npm fund` for details
[15:35:44] [DATA] 5 high severity vulnerabilities
[15:35:44] [DATA] To address all issues (including breaking changes), run:
[15:35:44] [DATA]   npm audit fix --force
[15:35:44] [DATA] Run `npm audit` for details.
[15:35:44] [SUCCESS] Installing dependencies using npm
[15:35:44] [START] Add dependencies using npm
[15:35:53] [DATA] added 47 packages, changed 4 packages, and audited 509 packages in 9s
[15:35:53] [DATA] 56 packages are looking for funding
[15:35:53] [DATA]   run `npm fund` for details
[15:35:53] [DATA] 5 high severity vulnerabilities
[15:35:53] [DATA] To address all issues (including breaking changes), run:
[15:35:53] [DATA]   npm audit fix --force
[15:35:53] [DATA] Run `npm audit` for details.
[15:35:53] [SUCCESS] Add dependencies using npm
[15:35:53] [START] Add devDependencies using npm
[15:36:16] [DATA] added 234 packages, and audited 743 packages in 23s
[15:36:16] [DATA] 77 packages are looking for funding
[15:36:16] [DATA]   run `npm fund` for details
[15:36:16] [DATA] 6 high severity vulnerabilities
[15:36:16] [DATA] To address issues that do not require attention, run:
[15:36:16] [DATA]   npm audit fix
[15:36:16] [DATA] To address all issues (including breaking changes), run:
[15:36:16] [DATA]   npm audit fix --force
[15:36:16] [DATA] Run `npm audit` for details.
[15:36:16] [SUCCESS] Add devDependencies using npm
[15:36:16] [START] Clean
[15:36:16] [SUCCESS] Clean
[15:36:16] [SUCCESS] Install
[15:36:16] [SUCCESS] Install plugins dependencies
[15:36:16] [START] Generate project files
[15:36:16] [START] Root files
[15:36:16] [DATA] [0/13] Rendering files...
[15:36:17] [DATA] [1/13] Rendering files...
[15:36:17] [DATA] [2/13] Rendering files...
[15:36:17] [DATA] [3/13] Rendering files...
[15:36:17] [DATA] [4/13] Rendering files...
[15:36:17] [DATA] [5/13] Rendering files...
[15:36:17] [DATA] [6/13] Rendering files...
[15:36:17] [DATA] [7/13] Rendering files...
[15:36:17] [DATA] [8/13] Rendering files...
[15:36:17] [DATA] [9/13] Rendering files...
[15:36:17] [DATA] [10/13] Rendering files...
[15:36:17] [DATA] [11/13] Rendering files...
[15:36:17] [DATA] [12/13] Rendering files...
[15:36:17] [DATA] [13/13] Rendering files...
[15:36:17] [DATA] [13/13] Rendering files...
[15:36:17] [SUCCESS] Root files
[15:36:17] [START] Generate server file to 'Server.ts'
[15:36:17] [SUCCESS] Generate server file to 'Server.ts'
[15:36:17] [START] Update bin/index
[15:36:17] [SKIP] Update bin/index
[15:36:17] [START] Generate server integration file 'Server.integration.spec.ts'
[15:36:17] [SUCCESS] Generate server integration file 'Server.integration.spec.ts'
[15:36:17] [START] Generate controller file to 'controllers/rest/HelloWorldController.ts'
[15:36:17] [SUCCESS] Generate controller file to 'controllers/rest/HelloWorldController.ts'
[15:36:17] [START] Update bin/index
[15:36:17] [SKIP] Update bin/index
[15:36:17] [START] Generate controller spec file to 'controllers/rest/HelloWorldController.spec.ts'
[15:36:17] [SUCCESS] Generate controller spec file to 'controllers/rest/HelloWorldController.spec.ts'
[15:36:17] [START] Generate controller integration file 'controllers/rest/HelloWorldController.integration.spec.ts'
[15:36:17] [SUCCESS] Generate controller integration file 'controllers/rest/HelloWorldController.integration.spec.ts'
[15:36:17] [SUCCESS] Generate project files
[15:36:17] [START] Generate files for eslint
[15:36:17] [DATA] [0/10] Rendering files...
[15:36:17] [DATA] [1/10] Rendering files...
[15:36:17] [DATA] [2/10] Rendering files...
[15:36:17] [DATA] [3/10] Rendering files...
[15:36:17] [DATA] [4/10] Rendering files...
[15:36:17] [DATA] [5/10] Rendering files...
[15:36:17] [DATA] [6/10] Rendering files...
[15:36:17] [DATA] [7/10] Rendering files...
[15:36:17] [DATA] [8/10] Rendering files...
[15:36:17] [DATA] [9/10] Rendering files...
[15:36:17] [DATA] [10/10] Rendering files...
[15:36:17] [DATA] [10/10] Rendering files...
[15:36:17] [SUCCESS] Generate files for eslint
[15:36:17] [START] Add dependencies
[15:36:17] [SUCCESS] Add dependencies
[15:36:17] [START] Generate files for jest
[15:36:17] [DATA] [0/1] Rendering files...
[15:36:17] [DATA] [1/1] Rendering files...
[15:36:17] [DATA] [1/1] Rendering files...
[15:36:17] [SUCCESS] Generate files for jest
[15:36:17] [START] Generate Prisma schema
Error: Command failed with exit code 1: npm run barrels
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/src/datasources'
    at Object.readdirSync (node:fs:1390:3)
    at buildTree (/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/fileTree.js:13:32)
    at /Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:46:51
    at Generator.next (<anonymous>)
    at /Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:5:12)
    at /Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:43:60
    at Array.forEach (<anonymous>)
    at Barrelsby (/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:43:25) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/src/datasources'
}

> default@1.0.0 barrels
> barrelsby --config .barrelsby.json

    at makeError (/Users/frederiquelemieux/dev/contributions/tsed-cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/frederiquelemieux/dev/contributions/tsed-cli/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: npm run barrels',
  command: 'npm run barrels',
  escapedCommand: 'npm run barrels',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n> default@1.0.0 barrels\n> barrelsby --config .barrelsby.json\n',
  stderr: 'node:fs:1390\n' +
    '  handleErrorFromBinding(ctx);\n' +
    '  ^\n' +
    '\n' +
    "Error: ENOENT: no such file or directory, scandir '/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/src/datasources'\n" +
    '    at Object.readdirSync (node:fs:1390:3)\n' +
    '    at buildTree (/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/fileTree.js:13:32)\n' +
    '    at /Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:46:51\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:9:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:5:12)\n' +
    '    at /Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:43:60\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Barrelsby (/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/node_modules/barrelsby/bin/index.js:43:25) {\n' +
    '  errno: -2,\n' +
    "  syscall: 'scandir',\n" +
    "  code: 'ENOENT',\n" +
    "  path: '/Users/frederiquelemieux/dev/contributions/tsed-cli/packages/cli/.tmp/init/default/src/datasources'\n" +
    '}',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
```
## Acceptance criteria

- [ ] Including TypeGraphQL doesn't fail tsed init.

**Comment by Romakita** [comment]
Hello @fredlemieux 
I reproduce the bug also. This regression was introduced with the 3.21.0 to support the future ESM architecture. I published yesterday some fixes for plugins. Unfortunately, the graphql plugin have another issue. 

You can try to downgrade the CLI to a version before 3.21.0. I'm on the fix ;)

See you
Romain

**Comment by Romakita** [comment]
Release is on going :)

**Comment by fredlemieux** [comment]
Amazing that was some serious quick fixing, thanks @Romakita. Just trying this out on a green field project, if it does the trick, I'll be shouting from the roof tops about ts.ED, great framework.  Hopefully I can repay the favour and contribute one of these days.

**Comment by fredlemieux** [comment]
Sorry to say, it isn't quite working. It worked with only the graphql feature selected, but when selecting the full monty of features it fell over:

Not to worry, in the meantime I can use the successful init with graphql and the successful init from the others and splice it together.  Not sure why it doesn't work all together thought... Let me know if there is anything I can do on my side.


```

? Choose the target platform: Express.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project TypeGraphQL, Database, Passport.j
s, Testing, Linter
? Choose a ORM manager Prisma
? Choose unit framework Jest
? Choose linter tools framework EsLint
? Choose extra linter tools Prettier, Lint on commit
? Choose the package manager: Yarn
↓ Write RC files [SKIPPED]
✔ Install plugins
⠇ Load plugins
◼ Install plugins dependencies
[20:18:38] ✔ @tsed/cli-plugin-eslint module loaded
↓ Write RC files [SKIPPED]
✔ Install plugins
✔ Load plugins
✔ Install plugins dependencies
✔ Generate project files
✔ Generate files for eslint
✔ Add dependencies
✔ Generate files for jest
⠹ Generate Prisma schema
◼ Add Ts.ED configuration to Prisma schema
◼ Generate files
◼ Install dependencies
◼ Add husky prepare task
/Users/frederiquelemieux/.nvm/versions/node/v18.4.0/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: yarn run barrels
warning package.json: No license field
node:fs:1450
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/src/datasources'
    at Object.readdirSync (node:fs:1450:3)
    at buildTree (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/fileTree.js:13:32)
    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:46:51
    at Generator.next (<anonymous>)
    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:5:12)
    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:43:60
    at Array.forEach (<anonymous>)
    at Barrelsby (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:43:25) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/src/datasources'
}

Node.js v18.4.0
error Command failed with exit code 1.
yarn run v1.22.17
$ barrelsby --config .barrelsby.json
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at makeError (/Users/frederiquelemieux/.nvm/versions/node/v18.4.0/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/frederiquelemieux/.nvm/versions/node/v18.4.0/lib/node_modules/@tsed/cli/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: yarn run barrels',
  command: 'yarn run barrels',
  escapedCommand: 'yarn run barrels',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn run v1.22.17\n' +
    '$ barrelsby --config .barrelsby.json\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.',
  stderr: 'warning package.json: No license field\n' +
    'node:fs:1450\n' +
    '  handleErrorFromBinding(ctx);\n' +
    '  ^\n' +
    '\n' +
    "Error: ENOENT: no such file or directory, scandir '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/src/datasources'\n" +
    '    at Object.readdirSync (node:fs:1450:3)\n' +
    '    at buildTree (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/fileTree.js:13:32)\n' +
    '    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:46:51\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:9:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:5:12)\n' +
    '    at /Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:43:60\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Barrelsby (/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/node_modules/barrelsby/bin/index.js:43:25) {\n' +
    '  errno: -2,\n' +
    "  syscall: 'scandir',\n" +
    "  code: 'ENOENT',\n" +
    "  path: '/Users/frederiquelemieux/dev/hoarelea/LivingLabAPI_v2/src/datasources'\n" +
    '}\n' +
    '\n' +
    'Node.js v18.4.0\n' +
    'error Command failed with exit code 1.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.4.0

```

**Comment by Romakita** [comment]
Ok I found the issue. The barrels command is run too early during code generation. Which interrupts the installation process. It's only when you select multiple options.

**Comment by Romakita** [comment]
Fixed :). The release in going.

**Comment by badaljain** [comment]
I still see the issue mentioned by @fredlemieux

**Comment by Romakita** [comment]
The fix is on going

**Comment by Romakita** [comment]
New release is out

**Comment by badaljain** [comment]
Thanks a lot :)
