### ISSUE TITLE
[BUG] Title - Tsed init failing while bootstrapping a new project

### ISSUE THREAD

**Issue by badaljain** [tsedio/tsed-cli#281]
## Information

- **Version:** 3.26.1
- Packages: all required in `tsed init
`
A few sentences describing the overall goals of the issue.
tsed init not working with the latest version and latest stable node version (16.17.0)

## Example

```ts
badals-MacBook-Pro-2:web-bff bads$ tsed init .
? Choose the target platform: Express.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project Swagger, Testing, Linter
? Choose unit framework Jest
? Choose linter tools framework EsLint
? Choose extra linter tools Prettier, Lint on commit
? Choose the package manager: NPM
↓ Write RC files [SKIPPED]
✔ Install plugins
↓ Write RC files [SKIPPED]
✔ Install plugins
✔ Load plugins
✔ Install plugins dependencies
✔ Generate project files
✔ Generate files for eslint
✔ Add dependencies
✔ Generate files for jest
✔ Install dependencies
✔ Add husky prepare task
✔ Generate barrels files
/usr/local/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: npm run barrels
node:fs:1442
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/bads/workspace/webstack/web-bff/src/resolvers'
    at Object.readdirSync (node:fs:1442:3)
    at buildTree (/Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/fileTree.js:13:32)
    at /Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:46:51
    at Generator.next (<anonymous>)
    at /Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:5:12)
    at /Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:43:60
    at Array.forEach (<anonymous>)
    at Barrelsby (/Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:43:25) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/bads/workspace/webstack/web-bff/src/resolvers'
}

> web-bff@1.0.0 barrels
> barrelsby --config .barrelsby.json

    at makeError (/usr/local/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/@tsed/cli/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: npm run barrels',
  command: 'npm run barrels',
  escapedCommand: 'npm run barrels',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n> web-bff@1.0.0 barrels\n> barrelsby --config .barrelsby.json\n',
  stderr: 'node:fs:1442\n' +
    '  handleErrorFromBinding(ctx);\n' +
    '  ^\n' +
    '\n' +
    "Error: ENOENT: no such file or directory, scandir '/Users/bads/workspace/webstack/web-bff/src/resolvers'\n" +
    '    at Object.readdirSync (node:fs:1442:3)\n' +
    '    at buildTree (/Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/fileTree.js:13:32)\n' +
    '    at /Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:46:51\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:9:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:5:12)\n' +
    '    at /Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:43:60\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Barrelsby (/Users/bads/workspace/webstack/web-bff/node_modules/barrelsby/bin/index.js:43:25) {\n' +
    '  errno: -2,\n' +
    "  syscall: 'scandir',\n" +
    "  code: 'ENOENT',\n" +
    "  path: '/Users/bads/workspace/webstack/web-bff/src/resolvers'\n" +
    '}',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

```

## Acceptance criteria

- [ ] tsed init works fine

**Comment by Romakita** [comment]
Hello @badaljain 
The barrelsby error can be fixed locally. Edit the barrelsby.json and remove directory that are not present in your project.

See you
Romain

**Comment by Romakita** [comment]
Remove resolvers line  ;)

**Comment by Romakita** [comment]
New release is out

**Comment by badaljain** [comment]
Thanks
