### ISSUE TITLE
Error creating a new project with Yarn V4.1.1

### ISSUE THREAD

**Issue by ygyg70** [tsedio/tsed-cli#378]
CLI version: 5.1.1
```
? Choose the target Framework: Express.js
? Choose the architecture for your project: Ts.ED
? Choose the convention file styling: Ts.ED
? Check the features needed for your project 
? Choose the runtime: Node.js
? Choose the package manager: Yarn
↓ Write RC files [SKIPPED]
✔ Initialize package.json
❯ Install plugins
  ✔ Write package.json
  ✔ Installing dependencies using yarn
  ✖ Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper @tsed/openspec @tsed/platform-cache @tsed/platform-…
    Unknown Syntax Error: Unsupported option name ("--ignore-engines").
    $ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
  ◼ Add devDependencies using yarn
  ◼ Refresh
◼ Load plugins
◼ Install plugins dependencies
Error: Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper @tsed/openspec @tsed/platform-cache @tsed/platform-exceptions @tsed/platform-log-middleware @tsed/platform-middlewares @tsed/platform-params @tsed/platform-response-filter @tsed/platform-views @tsed/logger @tsed/logger-file @tsed/engines ajv barrelsby cross-env dotenv dotenv-expand dotenv-flow @tsed/platform-express body-parser cors compression cookie-parser express method-override
Unknown Syntax Error: Unsupported option name ("--ignore-engines").

$ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
    at makeError (/usr/local/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/@tsed/cli/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  name: 'CLI_ERROR',
  cli: Cli { injector: [Getter], cliService: [Getter] },
  origin: Error: Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper @tsed/openspec @tsed/platform-cache @tsed/platform-exceptions @tsed/platform-log-middleware @tsed/platform-middlewares @tsed/platform-params @tsed/platform-response-filter @tsed/platform-views @tsed/logger @tsed/logger-file @tsed/engines ajv barrelsby cross-env dotenv dotenv-expand dotenv-flow @tsed/platform-express body-parser cors compression cookie-parser express method-override
  Unknown Syntax Error: Unsupported option name ("--ignore-engines").
  
  $ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
      at makeError (/usr/local/lib/node_modules/@tsed/cli/node_modules/execa/lib/error.js:60:11)
      at handlePromise (/usr/local/lib/node_modules/@tsed/cli/node_modules/execa/index.js:118:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    shortMessage: 'Command failed with exit code 1: yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper @tsed/openspec @tsed/platform-cache @tsed/platform-exceptions @tsed/platform-log-middleware @tsed/platform-middlewares @tsed/platform-params @tsed/platform-response-filter @tsed/platform-views @tsed/logger @tsed/logger-file @tsed/engines ajv barrelsby cross-env dotenv dotenv-expand dotenv-flow @tsed/platform-express body-parser cors compression cookie-parser express method-override',
    command: 'yarn add --ignore-engines @tsed/common @tsed/core @tsed/di @tsed/ajv @tsed/exceptions @tsed/schema @tsed/json-mapper @tsed/openspec @tsed/platform-cache @tsed/platform-exceptions @tsed/platform-log-middleware @tsed/platform-middlewares @tsed/platform-params @tsed/platform-response-filter @tsed/platform-views @tsed/logger @tsed/logger-file @tsed/engines ajv barrelsby cross-env dotenv dotenv-expand dotenv-flow @tsed/platform-express body-parser cors compression cookie-parser express method-override',
    escapedCommand: 'yarn add --ignore-engines "@tsed/common" "@tsed/core" "@tsed/di" "@tsed/ajv" "@tsed/exceptions" "@tsed/schema" "@tsed/json-mapper" "@tsed/openspec" "@tsed/platform-cache" "@tsed/platform-exceptions" "@tsed/platform-log-middleware" "@tsed/platform-middlewares" "@tsed/platform-params" "@tsed/platform-response-filter" "@tsed/platform-views" "@tsed/logger" "@tsed/logger-file" "@tsed/engines" ajv barrelsby cross-env dotenv dotenv-expand dotenv-flow "@tsed/platform-express" body-parser cors compression cookie-parser express method-override',
    exitCode: 1,
    signal: undefined,
    signalDescription: undefined,
    stdout: '\x1B[31m\x1B[1mUnknown Syntax Error\x1B[22m\x1B[39m: Unsupported option name ("--ignore-engines").\n' +
      '\n' +
      '$ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...',
    stderr: '',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
}

```

**Comment by Romakita** [comment]
Ho…. The flag have been removed 🥲
I’ll fix that. Thanks for the PR
